### ISSUE TITLE
Commit logs can use better colors.

### ISSUE THREAD

**Issue by karandesai-96** [AmmsA/Githeat#1]
![image](https://cloud.githubusercontent.com/assets/10494087/16676918/8c5af3f6-44ed-11e6-9f35-4adb22551d1b.png)

It would be nice to color the date, and somehow include the colors of `grass`, `fire` and `sky` altogether in the log, to keep it common.

**Comment by AmmsA** [comment]
Thanks for the suggestion! I was actually considering changing the color of the authors name to a color correlated to their contribution on that day.

I'll look more into it, shouldn't be hard to implement.
Cheers!

**Comment by AmmsA** [comment]
So I have two options, either fixed colors based on the current heatmap colors, with authors have the same color regardless of how many commits they commited on that day. 
<img width="1280" alt="screen shot 2016-07-08 at 12 52 01 am" src="https://cloud.githubusercontent.com/assets/748271/16677747/c7cdce6e-44a6-11e6-8f67-e4e65e8077e5.png">

or something like this, with authors colored depeneding on how many commits they've made on that day
<img width="1280" alt="screen shot 2016-07-08 at 12 55 37 am" src="https://cloud.githubusercontent.com/assets/748271/16677767/005a7f02-44a7-11e6-9109-96ce0bf110d6.png">

My only problem with the latter is that it's somewhat hard to read for some colors like the `grass` one, and it sorta feels like it makes the commit less important than other, which is totally not the intension.

Might go for the first one.

**Comment by karandesai-96** [comment]
I agree with the first one, as the commits are listed already on a per day basis. A constant color would be just fine. 
My suggestion would be keeping commit hash yellow, date green and author info blue. We can assign the colors randomly too. Another suggestion would be to keep all in shades of single color based on grass fire and sky.

**Comment by Georgiel** [comment]
Why not an option of changing theme by commands? Then it's best if both worlds

**Comment by AmmsA** [comment]
Made https://github.com/AmmsA/Githeat/commit/574a8a27d85b05a04b01f0ade9fab77f4bf86c13 regarding this. Will include in the next release. 

Closing for now.

**Comment by karandesai-96** [comment]
That's great ! Cheers :smiley:
