### ISSUE TITLE
python 3

### ISSUE THREAD

**Issue by jquast** [ammsa/Githeat#4]
I was able to get GitHeat to work on Python 3 with a few small changes, they're quite crude, I can submit them if you like?

I plan to feature this application in the README of blessed, so I was hoping you can let me know if it will continue to function, python 2 being EOL and all :(

**Comment by ammsa** [comment]
Hi @jquast,

Yes, I wanted to move it to python3 but didn't have the time. Can you submit and I'll take a look?

**Comment by ammsa** [comment]
be19afd fixes this. `pip3 install githeat` should work now.
